version: '3.8'

services:
  transcription-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: transcription-api:latest
    ports:
      - "80:80"
    volumes:
      - ./whisper_cache:/root/.cache/whisper
      - ./:/app/
    command: uvicorn app:app --host 0.0.0.0 --port 80
    #comment this to disable gpu
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
